const { hexToBits, strToBits } = require('../../shared/string')
const { des } = require('../../des')
const { bitsToHex, bitsToStr } = require('../../shared/bit')
const input = require('./input.json')

const pk = hexToBits(input.pk)
const block = strToBits(input.block)
const encrypted = des(pk, block)
const decrypted = des(pk, encrypted, true)

console.log('Block as string           :', bitsToStr(block))
console.log('Block as hex              :', bitsToHex(block))
console.log('Block as binary           :', block.join(''))
console.log('Key as string             :', bitsToStr(pk))
console.log('Key as hex                :', bitsToHex(pk))
console.log('Key as binary             :', pk.join(''))
console.log('Encrypted block as string :', bitsToStr(encrypted))
console.log('Encrytped block as hex    :', bitsToHex(encrypted))
console.log('Encrypted block as binary :', encrypted.join(''))
console.log('Decrypted block as string :', bitsToStr(decrypted))
console.log('Decrytped block as hex    :', bitsToHex(decrypted))
console.log('Decrypted block as binary :', decrypted.join(''))
