Object.assign(global, require('../des'))
Object.assign(global, require('../shared/bit'))
Object.assign(global, require('../shared/byte'))
Object.assign(global, require('../shared/big-int'))
global.curve = require('../shared/curve')
global.secp256k1 = require('../shared/secp256k1')
Object.assign(global, require('../shared/string'))
global.zn = require('../shared/zn')