Object.assign(global, require('../shared/bit'))
Object.assign(global, require('../shared/byte'))
Object.assign(global, require('../shared/gcd'))
Object.assign(global, require('../shared/string'))
Object.assign(global, require('../des'))